# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import subscribers_pb2 as subscribers__pb2


class SubscribersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSubscriber = channel.unary_unary(
                '/subscribers.SubscribersService/CreateSubscriber',
                request_serializer=subscribers__pb2.CreateSubscriberDto.SerializeToString,
                response_deserializer=subscribers__pb2.SubscriberResponse.FromString,
                )
        self.FindAllSubscribers = channel.unary_unary(
                '/subscribers.SubscribersService/FindAllSubscribers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=subscribers__pb2.FindAllSubscribersResponse.FromString,
                )
        self.FindOneSubscribers = channel.unary_unary(
                '/subscribers.SubscribersService/FindOneSubscribers',
                request_serializer=subscribers__pb2.FindOneSubscriberRequest.SerializeToString,
                response_deserializer=subscribers__pb2.SubscriberResponse.FromString,
                )


class SubscribersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSubscriber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAllSubscribers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindOneSubscribers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubscribersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSubscriber': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSubscriber,
                    request_deserializer=subscribers__pb2.CreateSubscriberDto.FromString,
                    response_serializer=subscribers__pb2.SubscriberResponse.SerializeToString,
            ),
            'FindAllSubscribers': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAllSubscribers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=subscribers__pb2.FindAllSubscribersResponse.SerializeToString,
            ),
            'FindOneSubscribers': grpc.unary_unary_rpc_method_handler(
                    servicer.FindOneSubscribers,
                    request_deserializer=subscribers__pb2.FindOneSubscriberRequest.FromString,
                    response_serializer=subscribers__pb2.SubscriberResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'subscribers.SubscribersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SubscribersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSubscriber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/subscribers.SubscribersService/CreateSubscriber',
            subscribers__pb2.CreateSubscriberDto.SerializeToString,
            subscribers__pb2.SubscriberResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindAllSubscribers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/subscribers.SubscribersService/FindAllSubscribers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            subscribers__pb2.FindAllSubscribersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindOneSubscribers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/subscribers.SubscribersService/FindOneSubscribers',
            subscribers__pb2.FindOneSubscriberRequest.SerializeToString,
            subscribers__pb2.SubscriberResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
