# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscribers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='subscribers.proto',
  package='subscribers',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11subscribers.proto\x12\x0bsubscribers\x1a\x1bgoogle/protobuf/empty.proto\"\x06\n\x04Void\"5\n\nSubscriber\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"A\n\x12SubscriberResponse\x12+\n\nsubscriber\x18\x01 \x01(\x0b\x32\x17.subscribers.Subscriber\"2\n\x13\x43reateSubscriberDto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"J\n\x1a\x46indAllSubscribersResponse\x12,\n\x0bsubscribers\x18\x01 \x03(\x0b\x32\x17.subscribers.Subscriber\"&\n\x18\x46indOneSubscriberRequest\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x0c\x45rrorMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\xa6\x02\n\x12SubscribersService\x12W\n\x10\x43reateSubscriber\x12 .subscribers.CreateSubscriberDto\x1a\x1f.subscribers.SubscriberResponse\"\x00\x12W\n\x12\x46indAllSubscribers\x12\x16.google.protobuf.Empty\x1a\'.subscribers.FindAllSubscribersResponse\"\x00\x12^\n\x12\x46indOneSubscribers\x12%.subscribers.FindOneSubscriberRequest\x1a\x1f.subscribers.SubscriberResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='subscribers.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=69,
)


_SUBSCRIBER = _descriptor.Descriptor(
  name='Subscriber',
  full_name='subscribers.Subscriber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='subscribers.Subscriber.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='subscribers.Subscriber.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='subscribers.Subscriber.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=124,
)


_SUBSCRIBERRESPONSE = _descriptor.Descriptor(
  name='SubscriberResponse',
  full_name='subscribers.SubscriberResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscriber', full_name='subscribers.SubscriberResponse.subscriber', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=191,
)


_CREATESUBSCRIBERDTO = _descriptor.Descriptor(
  name='CreateSubscriberDto',
  full_name='subscribers.CreateSubscriberDto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='subscribers.CreateSubscriberDto.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='subscribers.CreateSubscriberDto.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=243,
)


_FINDALLSUBSCRIBERSRESPONSE = _descriptor.Descriptor(
  name='FindAllSubscribersResponse',
  full_name='subscribers.FindAllSubscribersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscribers', full_name='subscribers.FindAllSubscribersResponse.subscribers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=319,
)


_FINDONESUBSCRIBERREQUEST = _descriptor.Descriptor(
  name='FindOneSubscriberRequest',
  full_name='subscribers.FindOneSubscriberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='subscribers.FindOneSubscriberRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=359,
)


_ERRORMESSAGE = _descriptor.Descriptor(
  name='ErrorMessage',
  full_name='subscribers.ErrorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='subscribers.ErrorMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='subscribers.ErrorMessage.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=408,
)

_SUBSCRIBERRESPONSE.fields_by_name['subscriber'].message_type = _SUBSCRIBER
_FINDALLSUBSCRIBERSRESPONSE.fields_by_name['subscribers'].message_type = _SUBSCRIBER
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['Subscriber'] = _SUBSCRIBER
DESCRIPTOR.message_types_by_name['SubscriberResponse'] = _SUBSCRIBERRESPONSE
DESCRIPTOR.message_types_by_name['CreateSubscriberDto'] = _CREATESUBSCRIBERDTO
DESCRIPTOR.message_types_by_name['FindAllSubscribersResponse'] = _FINDALLSUBSCRIBERSRESPONSE
DESCRIPTOR.message_types_by_name['FindOneSubscriberRequest'] = _FINDONESUBSCRIBERREQUEST
DESCRIPTOR.message_types_by_name['ErrorMessage'] = _ERRORMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'subscribers_pb2'
  # @@protoc_insertion_point(class_scope:subscribers.Void)
  })
_sym_db.RegisterMessage(Void)

Subscriber = _reflection.GeneratedProtocolMessageType('Subscriber', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBER,
  '__module__' : 'subscribers_pb2'
  # @@protoc_insertion_point(class_scope:subscribers.Subscriber)
  })
_sym_db.RegisterMessage(Subscriber)

SubscriberResponse = _reflection.GeneratedProtocolMessageType('SubscriberResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBERRESPONSE,
  '__module__' : 'subscribers_pb2'
  # @@protoc_insertion_point(class_scope:subscribers.SubscriberResponse)
  })
_sym_db.RegisterMessage(SubscriberResponse)

CreateSubscriberDto = _reflection.GeneratedProtocolMessageType('CreateSubscriberDto', (_message.Message,), {
  'DESCRIPTOR' : _CREATESUBSCRIBERDTO,
  '__module__' : 'subscribers_pb2'
  # @@protoc_insertion_point(class_scope:subscribers.CreateSubscriberDto)
  })
_sym_db.RegisterMessage(CreateSubscriberDto)

FindAllSubscribersResponse = _reflection.GeneratedProtocolMessageType('FindAllSubscribersResponse', (_message.Message,), {
  'DESCRIPTOR' : _FINDALLSUBSCRIBERSRESPONSE,
  '__module__' : 'subscribers_pb2'
  # @@protoc_insertion_point(class_scope:subscribers.FindAllSubscribersResponse)
  })
_sym_db.RegisterMessage(FindAllSubscribersResponse)

FindOneSubscriberRequest = _reflection.GeneratedProtocolMessageType('FindOneSubscriberRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDONESUBSCRIBERREQUEST,
  '__module__' : 'subscribers_pb2'
  # @@protoc_insertion_point(class_scope:subscribers.FindOneSubscriberRequest)
  })
_sym_db.RegisterMessage(FindOneSubscriberRequest)

ErrorMessage = _reflection.GeneratedProtocolMessageType('ErrorMessage', (_message.Message,), {
  'DESCRIPTOR' : _ERRORMESSAGE,
  '__module__' : 'subscribers_pb2'
  # @@protoc_insertion_point(class_scope:subscribers.ErrorMessage)
  })
_sym_db.RegisterMessage(ErrorMessage)



_SUBSCRIBERSSERVICE = _descriptor.ServiceDescriptor(
  name='SubscribersService',
  full_name='subscribers.SubscribersService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=411,
  serialized_end=705,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateSubscriber',
    full_name='subscribers.SubscribersService.CreateSubscriber',
    index=0,
    containing_service=None,
    input_type=_CREATESUBSCRIBERDTO,
    output_type=_SUBSCRIBERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FindAllSubscribers',
    full_name='subscribers.SubscribersService.FindAllSubscribers',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_FINDALLSUBSCRIBERSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FindOneSubscribers',
    full_name='subscribers.SubscribersService.FindOneSubscribers',
    index=2,
    containing_service=None,
    input_type=_FINDONESUBSCRIBERREQUEST,
    output_type=_SUBSCRIBERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUBSCRIBERSSERVICE)

DESCRIPTOR.services_by_name['SubscribersService'] = _SUBSCRIBERSSERVICE

# @@protoc_insertion_point(module_scope)
